apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: microservices
  annotations:
    # Per-minute rate limit (har IP se max 10 requests per minute)
    nginx.ingress.kubernetes.io/limit-rps: "5"

    # Connection limit (ek IP se max 5 concurrent connections)
    nginx.ingress.kubernetes.io/limit-connections: "5"

    # Burst limit (kitni extra requests allow karni hain temporary spike me)
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80

          - path: /api/profile
            pathType: Prefix
            backend:
              service:
                name: profile-service
                port:
                  number: 80

          - path: /api/email
            pathType: Prefix
            backend:
              service:
                name: email-service
                port:
                  number: 80

          - path: /api/analytics
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 80

          - path: /api/order
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 80