apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: microservices
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS auth_service_db;
    CREATE DATABASE IF NOT EXISTS profile_service_db;
    CREATE DATABASE IF NOT EXISTS order_service_db;
    CREATE DATABASE IF NOT EXISTS email_service_db;
    CREATE DATABASE IF NOT EXISTS analytics_service_db;