# ==========================================
# Application
# ==========================================
spring.application.name=APIGATEWAY-SERVICE
server.port=8080

# ==========================================
# Redis
# ==========================================
spring.data.redis.host=redis
spring.data.redis.port=6379

# ==========================================
# Auth Service
# ==========================================
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# Rate Limiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.replenishRate=100
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=200
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@ipKeyResolver}

# ==========================================
# Profile Service
# ==========================================
spring.cloud.gateway.server.webflux.routes[1].id=profile-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://profile-service:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/profile/**

# ==========================================
# Email Service
# ==========================================
spring.cloud.gateway.server.webflux.routes[2].id=email-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://email-service:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/email/**

# ==========================================
# Analytics Service
# ==========================================
spring.cloud.gateway.server.webflux.routes[3].id=analytics-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://analytics-service:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/analytics/**

# ==========================================
# Order Service
# ==========================================
spring.cloud.gateway.server.webflux.routes[4].id=order-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://order-service:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/order/**

